version: "3.3"

services:
  # mongodb:
  #   image : mongo
  #   container_name: lab-mongodb
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   #volumes:
  #   #  - mongodata:/data/db
  #   ports:  
  #     - 27017:27017
  #   restart: unless-stopped
  next-app: 
    container_name: next-app
    image: next-js-image
    ports:
      - 3000:3000  
  app: 
    container_name: plant-generator
    image: node-ts-image
    ports:
      - 5001:5001
    

  # mysql:
  #   image: mysql:latest
  #   container_name: lab-mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_DATABASE=CoreData
  #     - MYSQL_PASSWORD=Admin123!
  #     - MYSQL_USER=admin
  #     - MYSQL_ROOT_PASSWORD=123456
    #volumes:
    #  - mysqldata:/var/lib/mysql

  # redis:
  #   container_name: lab-redis
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

#volumes:
#  mongodata:
#    external: false  